'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace IRSTaxServices
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IRSTaxServicesSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class IRSTaxServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private authHeaderValueField As AuthHeader
        
        Private LoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UploadFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AuthenticateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCustomerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ClearAllErrorsBeforeDownloadingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCustomerFromListIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTotalNewCustomersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetNextNewCustomerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateCustomerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCompaniesWithPendingInvoicesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private MarkInvoiceUpdatedInQBOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPendingInvoiceOfCompanyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInvoiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLastBatchNumberOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInvoicesByListIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInvoicesByCustomerNameOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RevertLastBatchNumberOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OrderPadCurrentVersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OrderPadGetLatestVersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.OrderPad.My.MySettings.Default.OrderPad_IRSTaxServices_IRSTaxServices
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property AuthHeaderValue() As AuthHeader
            Get
                Return Me.authHeaderValueField
            End Get
            Set
                Me.authHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event LoginCompleted As LoginCompletedEventHandler
        
        '''<remarks/>
        Public Event UploadFileCompleted As UploadFileCompletedEventHandler
        
        '''<remarks/>
        Public Event AuthenticateCompleted As AuthenticateCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCustomerCompleted As GetCustomerCompletedEventHandler
        
        '''<remarks/>
        Public Event ClearAllErrorsBeforeDownloadingCompleted As ClearAllErrorsBeforeDownloadingCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCustomerFromListIdCompleted As GetCustomerFromListIdCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTotalNewCustomersCompleted As GetTotalNewCustomersCompletedEventHandler
        
        '''<remarks/>
        Public Event GetNextNewCustomerCompleted As GetNextNewCustomerCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCustomerCompleted As UpdateCustomerCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCompaniesWithPendingInvoicesCompleted As GetCompaniesWithPendingInvoicesCompletedEventHandler
        
        '''<remarks/>
        Public Event MarkInvoiceUpdatedInQBCompleted As MarkInvoiceUpdatedInQBCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPendingInvoiceOfCompanyCompleted As GetPendingInvoiceOfCompanyCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInvoiceCompleted As GetInvoiceCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLastBatchNumberCompleted As GetLastBatchNumberCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInvoicesByListIDCompleted As GetInvoicesByListIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInvoicesByCustomerNameCompleted As GetInvoicesByCustomerNameCompletedEventHandler
        
        '''<remarks/>
        Public Event RevertLastBatchNumberCompleted As RevertLastBatchNumberCompletedEventHandler
        
        '''<remarks/>
        Public Event OrderPadCurrentVersionCompleted As OrderPadCurrentVersionCompletedEventHandler
        
        '''<remarks/>
        Public Event OrderPadGetLatestVersionCompleted As OrderPadGetLatestVersionCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Login() As Customer
            Dim results() As Object = Me.Invoke("Login", New Object(-1) {})
            Return CType(results(0),Customer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LoginAsync()
            Me.LoginAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LoginAsync(ByVal userState As Object)
            If (Me.LoginOperationCompleted Is Nothing) Then
                Me.LoginOperationCompleted = AddressOf Me.OnLoginOperationCompleted
            End If
            Me.InvokeAsync("Login", New Object(-1) {}, Me.LoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.LoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LoginCompleted(Me, New LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UploadFile(ByVal fileName As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal fileContent() As Byte) As Integer
            Dim results() As Object = Me.Invoke("UploadFile", New Object() {fileName, fileContent})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UploadFileAsync(ByVal fileName As String, ByVal fileContent() As Byte)
            Me.UploadFileAsync(fileName, fileContent, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UploadFileAsync(ByVal fileName As String, ByVal fileContent() As Byte, ByVal userState As Object)
            If (Me.UploadFileOperationCompleted Is Nothing) Then
                Me.UploadFileOperationCompleted = AddressOf Me.OnUploadFileOperationCompleted
            End If
            Me.InvokeAsync("UploadFile", New Object() {fileName, fileContent}, Me.UploadFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnUploadFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.UploadFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UploadFileCompleted(Me, New UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Authenticate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Authenticate() As Boolean
            Dim results() As Object = Me.Invoke("Authenticate", New Object(-1) {})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AuthenticateAsync()
            Me.AuthenticateAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AuthenticateAsync(ByVal userState As Object)
            If (Me.AuthenticateOperationCompleted Is Nothing) Then
                Me.AuthenticateOperationCompleted = AddressOf Me.OnAuthenticateOperationCompleted
            End If
            Me.InvokeAsync("Authenticate", New Object(-1) {}, Me.AuthenticateOperationCompleted, userState)
        End Sub
        
        Private Sub OnAuthenticateOperationCompleted(ByVal arg As Object)
            If (Not (Me.AuthenticateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AuthenticateCompleted(Me, New AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCustomer(ByVal id As Integer) As Customer
            Dim results() As Object = Me.Invoke("GetCustomer", New Object() {id})
            Return CType(results(0),Customer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCustomerAsync(ByVal id As Integer)
            Me.GetCustomerAsync(id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCustomerAsync(ByVal id As Integer, ByVal userState As Object)
            If (Me.GetCustomerOperationCompleted Is Nothing) Then
                Me.GetCustomerOperationCompleted = AddressOf Me.OnGetCustomerOperationCompleted
            End If
            Me.InvokeAsync("GetCustomer", New Object() {id}, Me.GetCustomerOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCustomerOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCustomerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCustomerCompleted(Me, New GetCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearAllErrorsBeforeDownloading", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ClearAllErrorsBeforeDownloading() As Boolean
            Dim results() As Object = Me.Invoke("ClearAllErrorsBeforeDownloading", New Object(-1) {})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ClearAllErrorsBeforeDownloadingAsync()
            Me.ClearAllErrorsBeforeDownloadingAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ClearAllErrorsBeforeDownloadingAsync(ByVal userState As Object)
            If (Me.ClearAllErrorsBeforeDownloadingOperationCompleted Is Nothing) Then
                Me.ClearAllErrorsBeforeDownloadingOperationCompleted = AddressOf Me.OnClearAllErrorsBeforeDownloadingOperationCompleted
            End If
            Me.InvokeAsync("ClearAllErrorsBeforeDownloading", New Object(-1) {}, Me.ClearAllErrorsBeforeDownloadingOperationCompleted, userState)
        End Sub
        
        Private Sub OnClearAllErrorsBeforeDownloadingOperationCompleted(ByVal arg As Object)
            If (Not (Me.ClearAllErrorsBeforeDownloadingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ClearAllErrorsBeforeDownloadingCompleted(Me, New ClearAllErrorsBeforeDownloadingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerFromListId", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCustomerFromListId(ByVal listID As String) As Customer
            Dim results() As Object = Me.Invoke("GetCustomerFromListId", New Object() {listID})
            Return CType(results(0),Customer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCustomerFromListIdAsync(ByVal listID As String)
            Me.GetCustomerFromListIdAsync(listID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCustomerFromListIdAsync(ByVal listID As String, ByVal userState As Object)
            If (Me.GetCustomerFromListIdOperationCompleted Is Nothing) Then
                Me.GetCustomerFromListIdOperationCompleted = AddressOf Me.OnGetCustomerFromListIdOperationCompleted
            End If
            Me.InvokeAsync("GetCustomerFromListId", New Object() {listID}, Me.GetCustomerFromListIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCustomerFromListIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCustomerFromListIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCustomerFromListIdCompleted(Me, New GetCustomerFromListIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTotalNewCustomers", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTotalNewCustomers() As Integer
            Dim results() As Object = Me.Invoke("GetTotalNewCustomers", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTotalNewCustomersAsync()
            Me.GetTotalNewCustomersAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTotalNewCustomersAsync(ByVal userState As Object)
            If (Me.GetTotalNewCustomersOperationCompleted Is Nothing) Then
                Me.GetTotalNewCustomersOperationCompleted = AddressOf Me.OnGetTotalNewCustomersOperationCompleted
            End If
            Me.InvokeAsync("GetTotalNewCustomers", New Object(-1) {}, Me.GetTotalNewCustomersOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTotalNewCustomersOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTotalNewCustomersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTotalNewCustomersCompleted(Me, New GetTotalNewCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNextNewCustomer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetNextNewCustomer() As Customer
            Dim results() As Object = Me.Invoke("GetNextNewCustomer", New Object(-1) {})
            Return CType(results(0),Customer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetNextNewCustomerAsync()
            Me.GetNextNewCustomerAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetNextNewCustomerAsync(ByVal userState As Object)
            If (Me.GetNextNewCustomerOperationCompleted Is Nothing) Then
                Me.GetNextNewCustomerOperationCompleted = AddressOf Me.OnGetNextNewCustomerOperationCompleted
            End If
            Me.InvokeAsync("GetNextNewCustomer", New Object(-1) {}, Me.GetNextNewCustomerOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetNextNewCustomerOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetNextNewCustomerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetNextNewCustomerCompleted(Me, New GetNextNewCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCustomer", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateCustomer(ByVal c As Customer) As Boolean
            Dim results() As Object = Me.Invoke("UpdateCustomer", New Object() {c})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateCustomerAsync(ByVal c As Customer)
            Me.UpdateCustomerAsync(c, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCustomerAsync(ByVal c As Customer, ByVal userState As Object)
            If (Me.UpdateCustomerOperationCompleted Is Nothing) Then
                Me.UpdateCustomerOperationCompleted = AddressOf Me.OnUpdateCustomerOperationCompleted
            End If
            Me.InvokeAsync("UpdateCustomer", New Object() {c}, Me.UpdateCustomerOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateCustomerOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCustomerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCustomerCompleted(Me, New UpdateCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCompaniesWithPendingInvoices", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCompaniesWithPendingInvoices(ByVal dateFrom As Date, ByVal dateTo As Date) As Integer()
            Dim results() As Object = Me.Invoke("GetCompaniesWithPendingInvoices", New Object() {dateFrom, dateTo})
            Return CType(results(0),Integer())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCompaniesWithPendingInvoicesAsync(ByVal dateFrom As Date, ByVal dateTo As Date)
            Me.GetCompaniesWithPendingInvoicesAsync(dateFrom, dateTo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCompaniesWithPendingInvoicesAsync(ByVal dateFrom As Date, ByVal dateTo As Date, ByVal userState As Object)
            If (Me.GetCompaniesWithPendingInvoicesOperationCompleted Is Nothing) Then
                Me.GetCompaniesWithPendingInvoicesOperationCompleted = AddressOf Me.OnGetCompaniesWithPendingInvoicesOperationCompleted
            End If
            Me.InvokeAsync("GetCompaniesWithPendingInvoices", New Object() {dateFrom, dateTo}, Me.GetCompaniesWithPendingInvoicesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCompaniesWithPendingInvoicesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCompaniesWithPendingInvoicesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCompaniesWithPendingInvoicesCompleted(Me, New GetCompaniesWithPendingInvoicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarkInvoiceUpdatedInQB", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MarkInvoiceUpdatedInQB(ByVal OrderNumber As Integer, ByVal ListID As String, ByVal QBBatchNumber As Integer) As Boolean
            Dim results() As Object = Me.Invoke("MarkInvoiceUpdatedInQB", New Object() {OrderNumber, ListID, QBBatchNumber})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub MarkInvoiceUpdatedInQBAsync(ByVal OrderNumber As Integer, ByVal ListID As String, ByVal QBBatchNumber As Integer)
            Me.MarkInvoiceUpdatedInQBAsync(OrderNumber, ListID, QBBatchNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub MarkInvoiceUpdatedInQBAsync(ByVal OrderNumber As Integer, ByVal ListID As String, ByVal QBBatchNumber As Integer, ByVal userState As Object)
            If (Me.MarkInvoiceUpdatedInQBOperationCompleted Is Nothing) Then
                Me.MarkInvoiceUpdatedInQBOperationCompleted = AddressOf Me.OnMarkInvoiceUpdatedInQBOperationCompleted
            End If
            Me.InvokeAsync("MarkInvoiceUpdatedInQB", New Object() {OrderNumber, ListID, QBBatchNumber}, Me.MarkInvoiceUpdatedInQBOperationCompleted, userState)
        End Sub
        
        Private Sub OnMarkInvoiceUpdatedInQBOperationCompleted(ByVal arg As Object)
            If (Not (Me.MarkInvoiceUpdatedInQBCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent MarkInvoiceUpdatedInQBCompleted(Me, New MarkInvoiceUpdatedInQBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPendingInvoiceOfCompany", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPendingInvoiceOfCompany(ByVal dateFrom As Date, ByVal dateTo As Date, ByVal CompanyID As Integer) As Integer()
            Dim results() As Object = Me.Invoke("GetPendingInvoiceOfCompany", New Object() {dateFrom, dateTo, CompanyID})
            Return CType(results(0),Integer())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPendingInvoiceOfCompanyAsync(ByVal dateFrom As Date, ByVal dateTo As Date, ByVal CompanyID As Integer)
            Me.GetPendingInvoiceOfCompanyAsync(dateFrom, dateTo, CompanyID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPendingInvoiceOfCompanyAsync(ByVal dateFrom As Date, ByVal dateTo As Date, ByVal CompanyID As Integer, ByVal userState As Object)
            If (Me.GetPendingInvoiceOfCompanyOperationCompleted Is Nothing) Then
                Me.GetPendingInvoiceOfCompanyOperationCompleted = AddressOf Me.OnGetPendingInvoiceOfCompanyOperationCompleted
            End If
            Me.InvokeAsync("GetPendingInvoiceOfCompany", New Object() {dateFrom, dateTo, CompanyID}, Me.GetPendingInvoiceOfCompanyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPendingInvoiceOfCompanyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPendingInvoiceOfCompanyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPendingInvoiceOfCompanyCompleted(Me, New GetPendingInvoiceOfCompanyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoice", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInvoice(ByVal OrderNumber As Integer) As Invoice
            Dim results() As Object = Me.Invoke("GetInvoice", New Object() {OrderNumber})
            Return CType(results(0),Invoice)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInvoiceAsync(ByVal OrderNumber As Integer)
            Me.GetInvoiceAsync(OrderNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInvoiceAsync(ByVal OrderNumber As Integer, ByVal userState As Object)
            If (Me.GetInvoiceOperationCompleted Is Nothing) Then
                Me.GetInvoiceOperationCompleted = AddressOf Me.OnGetInvoiceOperationCompleted
            End If
            Me.InvokeAsync("GetInvoice", New Object() {OrderNumber}, Me.GetInvoiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInvoiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInvoiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInvoiceCompleted(Me, New GetInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastBatchNumber", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLastBatchNumber() As Integer
            Dim results() As Object = Me.Invoke("GetLastBatchNumber", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLastBatchNumberAsync()
            Me.GetLastBatchNumberAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLastBatchNumberAsync(ByVal userState As Object)
            If (Me.GetLastBatchNumberOperationCompleted Is Nothing) Then
                Me.GetLastBatchNumberOperationCompleted = AddressOf Me.OnGetLastBatchNumberOperationCompleted
            End If
            Me.InvokeAsync("GetLastBatchNumber", New Object(-1) {}, Me.GetLastBatchNumberOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLastBatchNumberOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLastBatchNumberCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLastBatchNumberCompleted(Me, New GetLastBatchNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoicesByListID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInvoicesByListID(ByVal ListID As String) As Invoice()
            Dim results() As Object = Me.Invoke("GetInvoicesByListID", New Object() {ListID})
            Return CType(results(0),Invoice())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInvoicesByListIDAsync(ByVal ListID As String)
            Me.GetInvoicesByListIDAsync(ListID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInvoicesByListIDAsync(ByVal ListID As String, ByVal userState As Object)
            If (Me.GetInvoicesByListIDOperationCompleted Is Nothing) Then
                Me.GetInvoicesByListIDOperationCompleted = AddressOf Me.OnGetInvoicesByListIDOperationCompleted
            End If
            Me.InvokeAsync("GetInvoicesByListID", New Object() {ListID}, Me.GetInvoicesByListIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInvoicesByListIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInvoicesByListIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInvoicesByListIDCompleted(Me, New GetInvoicesByListIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoicesByCustomerName", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInvoicesByCustomerName(ByVal CustomerName As String, ByVal orderDateFrom As Date, ByVal orderDateTo As Date) As Invoice()
            Dim results() As Object = Me.Invoke("GetInvoicesByCustomerName", New Object() {CustomerName, orderDateFrom, orderDateTo})
            Return CType(results(0),Invoice())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInvoicesByCustomerNameAsync(ByVal CustomerName As String, ByVal orderDateFrom As Date, ByVal orderDateTo As Date)
            Me.GetInvoicesByCustomerNameAsync(CustomerName, orderDateFrom, orderDateTo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInvoicesByCustomerNameAsync(ByVal CustomerName As String, ByVal orderDateFrom As Date, ByVal orderDateTo As Date, ByVal userState As Object)
            If (Me.GetInvoicesByCustomerNameOperationCompleted Is Nothing) Then
                Me.GetInvoicesByCustomerNameOperationCompleted = AddressOf Me.OnGetInvoicesByCustomerNameOperationCompleted
            End If
            Me.InvokeAsync("GetInvoicesByCustomerName", New Object() {CustomerName, orderDateFrom, orderDateTo}, Me.GetInvoicesByCustomerNameOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInvoicesByCustomerNameOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInvoicesByCustomerNameCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInvoicesByCustomerNameCompleted(Me, New GetInvoicesByCustomerNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RevertLastBatchNumber", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RevertLastBatchNumber() As Integer
            Dim results() As Object = Me.Invoke("RevertLastBatchNumber", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RevertLastBatchNumberAsync()
            Me.RevertLastBatchNumberAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RevertLastBatchNumberAsync(ByVal userState As Object)
            If (Me.RevertLastBatchNumberOperationCompleted Is Nothing) Then
                Me.RevertLastBatchNumberOperationCompleted = AddressOf Me.OnRevertLastBatchNumberOperationCompleted
            End If
            Me.InvokeAsync("RevertLastBatchNumber", New Object(-1) {}, Me.RevertLastBatchNumberOperationCompleted, userState)
        End Sub
        
        Private Sub OnRevertLastBatchNumberOperationCompleted(ByVal arg As Object)
            If (Not (Me.RevertLastBatchNumberCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RevertLastBatchNumberCompleted(Me, New RevertLastBatchNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrderPadCurrentVersion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OrderPadCurrentVersion() As String
            Dim results() As Object = Me.Invoke("OrderPadCurrentVersion", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OrderPadCurrentVersionAsync()
            Me.OrderPadCurrentVersionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OrderPadCurrentVersionAsync(ByVal userState As Object)
            If (Me.OrderPadCurrentVersionOperationCompleted Is Nothing) Then
                Me.OrderPadCurrentVersionOperationCompleted = AddressOf Me.OnOrderPadCurrentVersionOperationCompleted
            End If
            Me.InvokeAsync("OrderPadCurrentVersion", New Object(-1) {}, Me.OrderPadCurrentVersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnOrderPadCurrentVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.OrderPadCurrentVersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OrderPadCurrentVersionCompleted(Me, New OrderPadCurrentVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrderPadGetLatestVersion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OrderPadGetLatestVersion() As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("OrderPadGetLatestVersion", New Object(-1) {})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub OrderPadGetLatestVersionAsync()
            Me.OrderPadGetLatestVersionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OrderPadGetLatestVersionAsync(ByVal userState As Object)
            If (Me.OrderPadGetLatestVersionOperationCompleted Is Nothing) Then
                Me.OrderPadGetLatestVersionOperationCompleted = AddressOf Me.OnOrderPadGetLatestVersionOperationCompleted
            End If
            Me.InvokeAsync("OrderPadGetLatestVersion", New Object(-1) {}, Me.OrderPadGetLatestVersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnOrderPadGetLatestVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.OrderPadGetLatestVersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OrderPadGetLatestVersionCompleted(Me, New OrderPadGetLatestVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/", IsNullable:=false)>  _
    Partial Public Class AuthHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private userNameField As String
        
        Private passwordField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Invoice
        
        Private fldLoanNumberField As String
        
        Private taxyear2013Field As Boolean
        
        Private taxyear2014Field As Boolean
        
        Private taxyear2005Field As Boolean
        
        Private taxyear2006Field As Boolean
        
        Private taxyear2007Field As Boolean
        
        Private taxyear2008Field As Boolean
        
        Private taxyear2009Field As Boolean
        
        Private taxyear2011Field As Boolean
        
        Private taxyear2012Field As Boolean
        
        Private taxyear2010Field As Boolean
        
        Private listIDQuickBooksField As String
        
        Private orderNumberField As Integer
        
        Private listIdField As Decimal
        
        Private listTypeField As Decimal
        
        Private companyIDField As Integer
        
        Private customeriDField As Integer
        
        Private requestNameField As String
        
        Private secondNameField As String
        
        Private sSNNoField As String
        
        Private taxYear2003Field As Boolean
        
        Private taxYear2002Field As Boolean
        
        Private taxYear2001Field As Boolean
        
        Private taxYear2000Field As Boolean
        
        Private typeOfFormField As TypeOfForm
        
        Private emailField As String
        
        Private faxField As String
        
        Private faxnoField As String
        
        Private statusField As String
        
        Private dOBField As String
        
        Private sexField As String
        
        Private billingStatusField As Boolean
        
        Private deliveryDateField As Date
        
        Private pDFField As String
        
        Private orderdateField As Date
        
        Private taxyear2004Field As Boolean
        
        Private specialFlagField As String
        
        Private taxPayer1Field As String
        
        Private taxPayer2Field As String
        
        Private processorField As String
        
        '''<remarks/>
        Public Property fldLoanNumber() As String
            Get
                Return Me.fldLoanNumberField
            End Get
            Set
                Me.fldLoanNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2013() As Boolean
            Get
                Return Me.taxyear2013Field
            End Get
            Set
                Me.taxyear2013Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2014() As Boolean
            Get
                Return Me.taxyear2014Field
            End Get
            Set
                Me.taxyear2014Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2005() As Boolean
            Get
                Return Me.taxyear2005Field
            End Get
            Set
                Me.taxyear2005Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2006() As Boolean
            Get
                Return Me.taxyear2006Field
            End Get
            Set
                Me.taxyear2006Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2007() As Boolean
            Get
                Return Me.taxyear2007Field
            End Get
            Set
                Me.taxyear2007Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2008() As Boolean
            Get
                Return Me.taxyear2008Field
            End Get
            Set
                Me.taxyear2008Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2009() As Boolean
            Get
                Return Me.taxyear2009Field
            End Get
            Set
                Me.taxyear2009Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2011() As Boolean
            Get
                Return Me.taxyear2011Field
            End Get
            Set
                Me.taxyear2011Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2012() As Boolean
            Get
                Return Me.taxyear2012Field
            End Get
            Set
                Me.taxyear2012Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2010() As Boolean
            Get
                Return Me.taxyear2010Field
            End Get
            Set
                Me.taxyear2010Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListIDQuickBooks() As String
            Get
                Return Me.listIDQuickBooksField
            End Get
            Set
                Me.listIDQuickBooksField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderNumber() As Integer
            Get
                Return Me.orderNumberField
            End Get
            Set
                Me.orderNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListId() As Decimal
            Get
                Return Me.listIdField
            End Get
            Set
                Me.listIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListType() As Decimal
            Get
                Return Me.listTypeField
            End Get
            Set
                Me.listTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyID() As Integer
            Get
                Return Me.companyIDField
            End Get
            Set
                Me.companyIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustomeriD() As Integer
            Get
                Return Me.customeriDField
            End Get
            Set
                Me.customeriDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestName() As String
            Get
                Return Me.requestNameField
            End Get
            Set
                Me.requestNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecondName() As String
            Get
                Return Me.secondNameField
            End Get
            Set
                Me.secondNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SSNNo() As String
            Get
                Return Me.sSNNoField
            End Get
            Set
                Me.sSNNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TaxYear2003() As Boolean
            Get
                Return Me.taxYear2003Field
            End Get
            Set
                Me.taxYear2003Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TaxYear2002() As Boolean
            Get
                Return Me.taxYear2002Field
            End Get
            Set
                Me.taxYear2002Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TaxYear2001() As Boolean
            Get
                Return Me.taxYear2001Field
            End Get
            Set
                Me.taxYear2001Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TaxYear2000() As Boolean
            Get
                Return Me.taxYear2000Field
            End Get
            Set
                Me.taxYear2000Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property typeOfForm() As TypeOfForm
            Get
                Return Me.typeOfFormField
            End Get
            Set
                Me.typeOfFormField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Faxno() As String
            Get
                Return Me.faxnoField
            End Get
            Set
                Me.faxnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DOB() As String
            Get
                Return Me.dOBField
            End Get
            Set
                Me.dOBField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sex() As String
            Get
                Return Me.sexField
            End Get
            Set
                Me.sexField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillingStatus() As Boolean
            Get
                Return Me.billingStatusField
            End Get
            Set
                Me.billingStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeliveryDate() As Date
            Get
                Return Me.deliveryDateField
            End Get
            Set
                Me.deliveryDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PDF() As String
            Get
                Return Me.pDFField
            End Get
            Set
                Me.pDFField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Orderdate() As Date
            Get
                Return Me.orderdateField
            End Get
            Set
                Me.orderdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Taxyear2004() As Boolean
            Get
                Return Me.taxyear2004Field
            End Get
            Set
                Me.taxyear2004Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SpecialFlag() As String
            Get
                Return Me.specialFlagField
            End Get
            Set
                Me.specialFlagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TaxPayer1() As String
            Get
                Return Me.taxPayer1Field
            End Get
            Set
                Me.taxPayer1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TaxPayer2() As String
            Get
                Return Me.taxPayer2Field
            End Get
            Set
                Me.taxPayer2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Processor() As String
            Get
                Return Me.processorField
            End Get
            Set
                Me.processorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum TypeOfForm
        
        '''<remarks/>
        S_None
        
        '''<remarks/>
        S_1040
        
        '''<remarks/>
        S_1120
        
        '''<remarks/>
        S_1065
        
        '''<remarks/>
        S_W2
        
        '''<remarks/>
        S_1099
        
        '''<remarks/>
        S_SSN
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Customer
        
        Private addloannumberField As Integer
        
        Private iRSFeeField As Decimal
        
        Private creditCardActiveField As Boolean
        
        Private sSN_FeeField As Decimal
        
        Private parentIDField As Integer
        
        Private chargeSecondTaxPayerField As Boolean
        
        Private isErrorField As Boolean
        
        Private listIdField As String
        
        Private customerIDField As Integer
        
        Private companyNameField As String
        
        Private nameField As String
        
        Private telephoneField As String
        
        Private faxNumberField As String
        
        Private emailField As String
        
        Private billtoNameField As String
        
        Private addressField As String
        
        Private address1Field As String
        
        Private cityField As String
        
        Private stateField As String
        
        Private zipField As String
        
        Private referalField As String
        
        Private userIDField As String
        
        Private passwordField As String
        
        Private approvedField As Integer
        
        Private confDateField As Date
        
        Private confTimeField As String
        
        Private branchIDField As Integer
        
        Private statusField As Integer
        
        Private standardRateField As Integer
        
        Private rushRateField As Decimal
        
        Private showgrantField As Integer
        
        Private associate_idField As Integer
        
        Private bill4506Field As Decimal
        
        Private billSSNField As Decimal
        
        Private commission_AmountField As Decimal
        
        Private comm_4506Field As Decimal
        
        Private comm_SSNField As Decimal
        
        '''<remarks/>
        Public Property Addloannumber() As Integer
            Get
                Return Me.addloannumberField
            End Get
            Set
                Me.addloannumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IRSFee() As Decimal
            Get
                Return Me.iRSFeeField
            End Get
            Set
                Me.iRSFeeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreditCardActive() As Boolean
            Get
                Return Me.creditCardActiveField
            End Get
            Set
                Me.creditCardActiveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SSN_Fee() As Decimal
            Get
                Return Me.sSN_FeeField
            End Get
            Set
                Me.sSN_FeeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParentID() As Integer
            Get
                Return Me.parentIDField
            End Get
            Set
                Me.parentIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ChargeSecondTaxPayer() As Boolean
            Get
                Return Me.chargeSecondTaxPayerField
            End Get
            Set
                Me.chargeSecondTaxPayerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ListId() As String
            Get
                Return Me.listIdField
            End Get
            Set
                Me.listIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustomerID() As Integer
            Get
                Return Me.customerIDField
            End Get
            Set
                Me.customerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyName() As String
            Get
                Return Me.companyNameField
            End Get
            Set
                Me.companyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Telephone() As String
            Get
                Return Me.telephoneField
            End Get
            Set
                Me.telephoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FaxNumber() As String
            Get
                Return Me.faxNumberField
            End Get
            Set
                Me.faxNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BilltoName() As String
            Get
                Return Me.billtoNameField
            End Get
            Set
                Me.billtoNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address1() As String
            Get
                Return Me.address1Field
            End Get
            Set
                Me.address1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property State() As String
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Zip() As String
            Get
                Return Me.zipField
            End Get
            Set
                Me.zipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Referal() As String
            Get
                Return Me.referalField
            End Get
            Set
                Me.referalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserID() As String
            Get
                Return Me.userIDField
            End Get
            Set
                Me.userIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Approved() As Integer
            Get
                Return Me.approvedField
            End Get
            Set
                Me.approvedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property confDate() As Date
            Get
                Return Me.confDateField
            End Get
            Set
                Me.confDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property confTime() As String
            Get
                Return Me.confTimeField
            End Get
            Set
                Me.confTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BranchID() As Integer
            Get
                Return Me.branchIDField
            End Get
            Set
                Me.branchIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property standardRate() As Integer
            Get
                Return Me.standardRateField
            End Get
            Set
                Me.standardRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rushRate() As Decimal
            Get
                Return Me.rushRateField
            End Get
            Set
                Me.rushRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property showgrant() As Integer
            Get
                Return Me.showgrantField
            End Get
            Set
                Me.showgrantField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Associate_id() As Integer
            Get
                Return Me.associate_idField
            End Get
            Set
                Me.associate_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bill4506() As Decimal
            Get
                Return Me.bill4506Field
            End Get
            Set
                Me.bill4506Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillSSN() As Decimal
            Get
                Return Me.billSSNField
            End Get
            Set
                Me.billSSNField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Commission_Amount() As Decimal
            Get
                Return Me.commission_AmountField
            End Get
            Set
                Me.commission_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Comm_4506() As Decimal
            Get
                Return Me.comm_4506Field
            End Get
            Set
                Me.comm_4506Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Comm_SSN() As Decimal
            Get
                Return Me.comm_SSNField
            End Get
            Set
                Me.comm_SSNField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub LoginCompletedEventHandler(ByVal sender As Object, ByVal e As LoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Customer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Customer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub UploadFileCompletedEventHandler(ByVal sender As Object, ByVal e As UploadFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UploadFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub AuthenticateCompletedEventHandler(ByVal sender As Object, ByVal e As AuthenticateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AuthenticateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetCustomerCompletedEventHandler(ByVal sender As Object, ByVal e As GetCustomerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCustomerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Customer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Customer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub ClearAllErrorsBeforeDownloadingCompletedEventHandler(ByVal sender As Object, ByVal e As ClearAllErrorsBeforeDownloadingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ClearAllErrorsBeforeDownloadingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetCustomerFromListIdCompletedEventHandler(ByVal sender As Object, ByVal e As GetCustomerFromListIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCustomerFromListIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Customer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Customer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetTotalNewCustomersCompletedEventHandler(ByVal sender As Object, ByVal e As GetTotalNewCustomersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTotalNewCustomersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetNextNewCustomerCompletedEventHandler(ByVal sender As Object, ByVal e As GetNextNewCustomerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetNextNewCustomerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Customer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Customer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub UpdateCustomerCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateCustomerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateCustomerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetCompaniesWithPendingInvoicesCompletedEventHandler(ByVal sender As Object, ByVal e As GetCompaniesWithPendingInvoicesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCompaniesWithPendingInvoicesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub MarkInvoiceUpdatedInQBCompletedEventHandler(ByVal sender As Object, ByVal e As MarkInvoiceUpdatedInQBCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class MarkInvoiceUpdatedInQBCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetPendingInvoiceOfCompanyCompletedEventHandler(ByVal sender As Object, ByVal e As GetPendingInvoiceOfCompanyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPendingInvoiceOfCompanyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetInvoiceCompletedEventHandler(ByVal sender As Object, ByVal e As GetInvoiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInvoiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Invoice
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Invoice)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetLastBatchNumberCompletedEventHandler(ByVal sender As Object, ByVal e As GetLastBatchNumberCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLastBatchNumberCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetInvoicesByListIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetInvoicesByListIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInvoicesByListIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Invoice()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Invoice())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub GetInvoicesByCustomerNameCompletedEventHandler(ByVal sender As Object, ByVal e As GetInvoicesByCustomerNameCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInvoicesByCustomerNameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Invoice()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Invoice())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub RevertLastBatchNumberCompletedEventHandler(ByVal sender As Object, ByVal e As RevertLastBatchNumberCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RevertLastBatchNumberCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub OrderPadCurrentVersionCompletedEventHandler(ByVal sender As Object, ByVal e As OrderPadCurrentVersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OrderPadCurrentVersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub OrderPadGetLatestVersionCompletedEventHandler(ByVal sender As Object, ByVal e As OrderPadGetLatestVersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OrderPadGetLatestVersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
End Namespace
