'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Statistics

    '''<summary>
    '''hypBackToHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypBackToHome As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''msg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msg As Global.IRSTaxRecords.Core.WebControls.WebPageMessage

    '''<summary>
    '''pnlSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dtFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtFromDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''dtToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtToDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''btnShowResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowResults As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlSearchREsults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchREsults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTotalOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalOrders As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAvgTurnTimeForAllOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvgTurnTimeForAllOrders As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFastestTurnTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFastestTurnTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdMain As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lblTotalNumberOfRejcts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalNumberOfRejcts As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRejectReason_InvalidAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectReason_InvalidAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRejectReason_SSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectReason_SSN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRejectReason_NameNotMatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectReason_NameNotMatch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRejectReason_UnProcessable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectReason_UnProcessable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRejectReason_Illegible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectReason_Illegible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRejectReason_Altered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectReason_Altered As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRejectReason_InvalidDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectReason_InvalidDate As Global.System.Web.UI.WebControls.Label
End Class
